name: "Java CI with Maven"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JDK and Maven
        run: |
          pacman -Sy --noconfirm jdk-openjdk maven

      - name: Set Java Home and add to PATH
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/default" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: Build with Maven
        run: mvn -B -f './backend_service/pom.xml' package

      - name: Update dependency graph
        run: mvn -f backend_service/pom.xml com.github.ferstl:depgraph-maven-plugin:4.0.1:graph

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          json_file: ./test_results/backend.json
          json_test_case_results: true
          files: |
            ./backend_service/target/surefire-reports/*.xml
